### ISSUE TITLE
INVALID_API_REQUEST Errors: [fields ['request_id'] may not be empty]

### ISSUE THREAD

**Issue by XanderZhu** [cardpay/android-sdk-demo#11]
I'm trying to use Unlimint SDK. I catch an error when calling UnlimintSdk.payForResult: **com.unlimint.sdk.ui.api.exceptions.UnlimintSdkException$InvalidData: {"name":"INVALID_API_REQUEST","message":"Errors: [fields ['request_id'] may not be empty]"}**.

I'm using 1.8.2 version.

What I'm doing wrong?

Full code: 

```
private val payForResult =
        registerForActivityResult(ActivityResultContracts.StartActivityForResult()) { result ->
            val intent = result.data ?: return@registerForActivityResult
            when(result.resultCode) {
                Activity.RESULT_OK -> {
                    val last4Digits = intent.getStringExtra(UnlimintSdk.ARG_LAST_4_DIGITS)
                    val transactionId = intent.getStringExtra(UnlimintSdk.TransactionData.TRANSACTION_ID)
                    logger.info("last4Digits=$last4Digits, transactionId=$transactionId")
                }
                Activity.RESULT_CANCELED -> {
                    val transactionId = intent.getStringExtra(UnlimintSdk.TransactionData.TRANSACTION_ID)
                    val exception = intent.getSerializableExtra(UnlimintSdk.ARG_EXCEPTION)
                    logger.info("exception=$exception, transactionId=$transactionId")
                }
            }
        }


UnlimintSdk.payForResult(
                activity = requireActivity() as AppCompatActivity,
                mobileAuthorizationToken = token,
                environment = Environments.SANDBOX,
                launcher = payForResult,
                paymentMethodsData = arrayListOf(
                    BankCardData(
                        customer = Customer(
                            id = "656945944",
                            email = "cardpay.test.mobile@gmail.com"
                        ),
                        merchantName = "merchantName",
                        merchantOrder = MerchantOrder("description", merchantOrderId),
                        paymentData = PaymentData(
                            amount = Amount(
                                value = BigDecimal.valueOf(50.0),
                                currency = Currency.getInstance("USD")
                            )
                        )
                    )
                )
            )
```

**Comment by taptappub** [comment]
Hi @XanderZhu 
We've found the problem, so I think, we'll fix it in 1 day. I'll write here when you can try the SDK again.

**Comment by taptappub** [comment]
Hello @XanderZhu
Could you try it again?

**Comment by XanderZhu** [comment]
@taptappub 
Ок, one moment

**Comment by XanderZhu** [comment]
@taptappub 
Thanks! Problem is solved.
But now there is another problem: `com.unlimint.sdk.ui.api.exceptions.UnlimintSdkException$InvalidData: {"name":"INVALID_API_REQUEST","message":"User does not have necessary role"}.` But I think I need to configure my sanbox account.

**Comment by taptappub** [comment]
@XanderZhu Did you try just to build the app with default credentials?

**Comment by XanderZhu** [comment]
@taptappub No, I didn't. 
I just copy code from the example app.
Where should I use default credentials and where can I find them?

**Comment by taptappub** [comment]
@XanderZhu Have you got this token`mobileAuthorizationToken = token,` from https://sandbox.cardpay.com/demo-merchant/ endpoint?

**Comment by XanderZhu** [comment]
@XanderZhu 
I got `mobileAuthorizationToken` from our backend, which take it via `https://sandbox.cardpay.com/api/mobile/token` endpoint.

**Comment by taptappub** [comment]
@XanderZhu 
I see. If you want to try the SDK, you can get mobileAuthorizationToken from https://sandbox.cardpay.com/demo-merchant/ (You can see the example in this repo), but with your problem, you should write to our support, they will help you with your sandbox account

**Comment by XanderZhu** [comment]
@taptappub Thanks fo help!
